<MyProgram>

    #outside: inside
    code: code

    BoxLayout:
        size: root.width, root.height
        BoxLayout:
            orientation: "vertical"

            CodeInput:
                id: code

            CodeInput:
                text: "Log"

            Button:
                text: "Interpret"
                size_hint_y: None
                height: 100
                on_press: root.get_code()

        Widget:

